### ISSUE TITLE
Cannot add or update a child row: a foreign key constraint fails (when updating contributions)

### ISSUE THREAD

**Issue by bjendres** [Project60/org.project60.banking#358]
The "Existing Contribution Matcher" (and maybe others, too) faces a weird issue: updating the contribution by ``id`` (via ``Contribution.create``) causes a "constraint violation" error. It seems that the ``contact_id`` does not get derived from the contribution ID in some scenarios. This might have to do with some shortcomings in the APIv4 (in CiviCRM ``5.37.2``).

Here's the stacktrace (CiviCRM ``5.37.2``):
```
May 09 15:04:54  [error] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => exceptionHandler
        )

    [code] => -3
    [message] => DB Error: constraint violation
    [mode] => 16
    [debug_info] => INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `record_type_id` ) VALUES ( 5914257 ,  0 ,  3 )  [nativecode=1452 ** Cannot add or update a child row: a foreign key constraint fails (`xxcivi1_db`.`civicrm_activity_contact`, CONSTRAINT `FK_civicrm_activity_contact_contact_id` FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE CASCADE)]
    [type] => DB_Error
    [user_info] => INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `record_type_id` ) VALUES ( 5914257 ,  0 ,  3 )  [nativecode=1452 ** Cannot add or update a child row: a foreign key constraint fails (`xxcivi1_db`.`civicrm_activity_contact`, CONSTRAINT `FK_civicrm_activity_contact_contact_id` FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE CASCADE)]
    [to_string] => [db_error: message="DB Error: constraint violation" code=-3 mode=callback callback=CRM_Core_Error::exceptionHandler prefix="" info="INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `record_type_id` ) VALUES ( 5914257 ,  0 ,  3 )  [nativecode=1452 ** Cannot add or update a child row: a foreign key constraint fails (`xxcivi1_db`.`civicrm_activity_contact`, CONSTRAINT `FK_civicrm_activity_contact_contact_id` FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact` (`id`) ON DELETE CASCADE)]"]
)

May 09 15:04:54  [debug] $backTrace = 
#0 sites/all/modules/civicrm/CRM/Core/Error.php(942): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(922): CRM_Core_Error::exceptionHandler(Object(DB_Error))
#2 sites/all/modules/civicrm/vendor/pear/db/DB.php(998): PEAR_Error->__construct("DB Error: constraint violation", -3, 16, (Array:2), "INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `recor...")
#3 sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(575): DB_Error->__construct(-3, 16, (Array:2), "INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `recor...")
#4 sites/all/modules/civicrm/vendor/pear/pear-core-minimal/src/PEAR.php(223): PEAR->_raiseError(Object(DB_mysqli), NULL, -3, 16, (Array:2), "INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `recor...", "DB_Error", TRUE)
#5 sites/all/modules/civicrm/vendor/pear/db/DB/common.php(1928): PEAR->__call("raiseError", (Array:7))
#6 sites/all/modules/civicrm/vendor/pear/db/DB/mysqli.php(936): DB_common->raiseError(-3, NULL, NULL, "INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `recor...", "1452 ** Cannot add or update a child row: a foreign key constraint fails (`xx...")
#7 sites/all/modules/civicrm/vendor/pear/db/DB/mysqli.php(406): DB_mysqli->mysqliRaiseError()
#8 sites/all/modules/civicrm/vendor/pear/db/DB/common.php(1234): DB_mysqli->simpleQuery("INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `recor...")
#9 sites/all/modules/civicrm/packages/DB/DataObject.php(2696): DB_common->query("INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `recor...")
#10 sites/all/modules/civicrm/packages/DB/DataObject.php(1245): DB_DataObject->_query("INSERT INTO `civicrm_activity_contact` (`activity_id` , `contact_id` , `recor...")
#11 sites/all/modules/civicrm/CRM/Core/DAO.php(639): DB_DataObject->insert()
#12 sites/all/modules/civicrm/CRM/Core/DAO.php(905): CRM_Core_DAO->save()
#13 sites/all/modules/civicrm/CRM/Activity/BAO/ActivityContact.php(37): CRM_Core_DAO::writeRecord((Array:4))
#14 sites/all/modules/civicrm/Civi/Api4/Generic/Traits/DAOActionTrait.php(140): CRM_Activity_BAO_ActivityContact::create((Array:4))
#15 sites/all/modules/civicrm/Civi/Api4/Generic/DAOSaveAction.php(41): Civi\Api4\Generic\DAOSaveAction->writeObjects((Array:2))
#16 sites/all/modules/civicrm/Civi/Api4/Provider/ActionObjectProvider.php(68): Civi\Api4\Generic\DAOSaveAction->_run(Object(Civi\Api4\Generic\Result))
#17 sites/all/modules/civicrm/Civi/API/Kernel.php(149): Civi\Api4\Provider\ActionObjectProvider->invoke(Object(Civi\Api4\Generic\DAOSaveAction))
#18 sites/all/modules/civicrm/Civi/Api4/Generic/AbstractAction.php(239): Civi\API\Kernel->runRequest(Object(Civi\Api4\Generic\DAOSaveAction))
#19 sites/all/modules/civicrm/CRM/Activity/BAO/Activity.php(404): Civi\Api4\Generic\AbstractAction->execute()
#20 sites/all/modules/civicrm/Civi/Api4/Generic/Traits/DAOActionTrait.php(140): CRM_Activity_BAO_Activity::create((Array:12))
#21 sites/all/modules/civicrm/Civi/Api4/Generic/DAOSaveAction.php(41): Civi\Api4\Generic\DAOSaveAction->writeObjects((Array:1))
#22 sites/all/modules/civicrm/Civi/Api4/Provider/ActionObjectProvider.php(68): Civi\Api4\Generic\DAOSaveAction->_run(Object(Civi\Api4\Generic\Result))
#23 sites/all/modules/civicrm/Civi/API/Kernel.php(149): Civi\Api4\Provider\ActionObjectProvider->invoke(Object(Civi\Api4\Generic\DAOSaveAction))
#24 sites/all/modules/civicrm/Civi/Api4/Generic/AbstractAction.php(239): Civi\API\Kernel->runRequest(Object(Civi\Api4\Generic\DAOSaveAction))
#25 sites/all/modules/civicrm/CRM/Contribute/BAO/Contribution.php(554): Civi\Api4\Generic\AbstractAction->execute()
#26 sites/all/modules/civicrm/api/v3/utils.php(1298): CRM_Contribute_BAO_Contribution::create((Array:20), (Array:1))
#27 sites/all/modules/civicrm/api/v3/Contribution.php(77): _civicrm_api3_basic_create("CRM_Contribute_BAO_Contribution", (Array:20), "Contribution")
#28 sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_contribution_create((Array:20))
#29 sites/all/modules/civicrm/Civi/API/Kernel.php(149): Civi\API\Provider\MagicFunctionProvider->invoke((Array:8))
#30 sites/all/modules/civicrm/Civi/API/Kernel.php(81): Civi\API\Kernel->runRequest((Array:8))
#31 sites/all/modules/civicrm/api/api.php(22): Civi\API\Kernel->runSafe("Contribution", "create", (Array:8))
#32 sites/default/files/civicrm/ext/org.project60.banking/CRM/Banking/PluginImpl/Matcher/ExistingContribution.php(425): civicrm_api("Contribution", "create", (Array:8))
#33 sites/default/files/civicrm/ext/org.project60.banking/CRM/Banking/Matcher/Suggestion.php(262): CRM_Banking_PluginImpl_Matcher_ExistingContribution->execute(Object(CRM_Banking_Matcher_Suggestion), Object(CRM_Banking_BAO_BankTransaction))
#34 sites/default/files/civicrm/ext/org.project60.banking/CRM/Banking/Page/Review.php(443): CRM_Banking_Matcher_Suggestion->execute(Object(CRM_Banking_BAO_BankTransaction))
#35 sites/default/files/civicrm/ext/org.project60.banking/CRM/Banking/Page/Review.php(74): CRM_Banking_Page_Review->execute_suggestion("S-17-2621929-existing-5377075", (Array:3), Object(CRM_Banking_BAO_BankTransaction), (Array:9))
#36 sites/all/modules/civicrm/CRM/Core/Invoke.php(313): CRM_Banking_Page_Review->run((Array:3), NULL)
#37 sites/all/modules/civicrm/CRM/Core/Invoke.php(69): CRM_Core_Invoke::runItem((Array:13))
#38 sites/all/modules/civicrm/CRM/Core/Invoke.php(36): CRM_Core_Invoke::_invoke((Array:3))
#39 sites/all/modules/civicrm/drupal/civicrm.module(458): CRM_Core_Invoke::invoke((Array:3))
#40 includes/menu.inc(527): civicrm_invoke("banking", "review")
#41 index.php(21): menu_execute_active_handler()
#42 {main}
```

**Comment by jensschuppe** [comment]
Would be interesting to see what exact parameters are being fed into the API here:

`#32 sites/default/files/civicrm/ext/org.project60.banking/CRM/Banking/PluginImpl/Matcher/ExistingContribution.php(425): civicrm_api("Contribution", "create", (Array:8))`

Maybe there's a `contact_id` parameter with a `0` or otherwise falsy value?

**Comment by bjendres** [comment]
> Would be interesting to see what exact parameters are being fed into the API here:

Nothing unexpected:
```
{
    "contribution_status_id": "1",
    "custom_349": "2022-04-27",
    "custom_72": "BE975XXXXXXXXX",
    "fee_amount": 0.475,
    "id": 5377075,
    "payment_instrument_id": "30",
    "receive_date": "20220426121608",
    "version": 3
}
```

And and it's been working nicely for years before the CiviCRM upgrade.

**Comment by bjendres** [comment]
Looks like it works just fine with the ``contact_id`` explicitly passed, but I'm assuming that this is a quirk of ``5.37.2`` and has long been weeded out.

I've added some mitigation code to a couple of calls in CiviBanking, and I'll add it to a couple more should this crop up somewhere else.
